# Site settings
title: "Manas Kashyap"
email: manaskashyaptech@gmail.com
description: "A Developer at building phase."
baseurl: ""
url: "https://Manas-kashyap.github.io"
title_description: "I am currently a DevOps Engineer at Byjus Exam Prep (Gradestack) 
<br /> I completed my undergrad from Amity University, Noida, India in Bachelor of Computer Science and Technology.
<br /> <strong>I am also a GSoC STUDENT under Debian (2020) (Android SDK Project)</strong>
<br /> An open-source enthusiast & a passionate learner. I also like to contribute to open source projects (like Android-development, Web development , dockers).
<br /> I am part of debian javascript , ruby , go , android , java , Medical , python and pkg security team .
<br /> I am also Developer in Hamaralinux.org and yogdaan.org (open source community) and I really like to learn new technologies and likes to experiment with them. 
<br /> My field of learning is more inclined toward the DevOps Side."
title_image: "https://www.gravatar.com/avatar/adfc6106200af1c797247b4944d67709?s=500&d=mm"
google_analytics: "UA-20365477-4"
disqus_account: manas-kashyap-github-io
github_repository: https://github.com/Manas-kashyap/Manas-kashyap.github.io/
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: manas_tech
github_username:  Manas-kashyap
instagram_username: nerdy.404
reddit_username: https://www.reddit.com/user/manas-kashyap/
linkedin_link: https://linkedin.com/in/manas-kashyap-1a2262130/
#google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
stackoverflow_link: https://stackoverflow.com/users/10564308/manas-kashyap
#xing_link:
#facebook_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/manas_tech\">Manas Kashyap</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/Manas-kashyap\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
